version: '3.7'
services:
    webdav:
        container_name: "webdav"
        restart: always
        image: ucipass/webdav
        stdin_open: true # docker run -i
        tty: true        # docker run -t        
        build:
            context: .
            dockerfile: Dockerfile    
        image: ucipass/webdav
        environment: 
        - USER=test
        - PASS=test123
        # command: "/root/dyndns.sh"
        ports:
        # Graylog web interface and REST API
        - 8080:80