version: '3'
services:
  ipsec:
    image: ucipass/ipsec
    build:
      context: .
      dockerfile: Dockerfile    
    container_name: "ipsec"     
    privileged: true
    environment:
      # CUSTOMIZE THESE ENV VARIABLES! 
      - VPN_GATEWAY=X.X.X.X
      - VPN_SECRET=secretkey
      - PRIV_REMOTE_NET=10.1.0.0/16
      - PRIV_LOCAL_NET=192.168.1.0/26
      - PRIV_LOCAL_IP=192.168.1.1/26
      - IKE=aes128-sha-modp1024,aes256-sha-modp1024,aes256-sha256-modp1024,3des-sha1-modp1024,aes256-sha1-modp1024!
      - IKE_LIFETIME=8h
      - ESP=aes-sha-modp1024,aes256-sha-modp1024,aes256-sha256,3des-sha1,aes256-sha1!
      - ESP_LIFETIME=1h      
    ports:
      - 4500:4500/udp
      - 500:500/udp
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
