version: '3'
services:
  ipsec:
    image: ucipass/ipsec
    build:
      context: .
      dockerfile: Dockerfile    
    container_name: "ipsec"     
    privileged: true
    environment:
      # CUSTOMIZE THESE ENV VARIABLES! 
      - VPN_GATEWAY=5.5.5.5
      - VPN_SECRET="SECRETKEYHERE"
      - PRIV_REMOTE_NET=10.1.0.0/16
      - PRIV_LOCAL_NET=192.168.1.0/26
      - PRIV_LOCAL_IP=192.168.1.1/26
      # OPTIONAL SECOND REMOTE NET
      #- PRIV_REMOTE_NET2=10.1.2.0/24
      - IKE=aes128-sha-modp1024,aes256-sha-modp1024,aes256-sha256-modp1024,3des-sha1-modp1024,aes256-sha1-modp1024!
      - IKE_LIFETIME=8h
      - ESP=aes-sha-modp1024,aes256-sha-modp1024,aes256-sha256,3des-sha1,aes256-sha1!
      - ESP_LIFETIME=1h      
    ports:
      # NAT-T
      - 4500:4500
      # IKE
      - 500:500
    # entrypoint: "tail -f /dev/null"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
