on: 
  push:
    paths:
    - 'debian*'
jobs:
  push-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Docker Build & Publish SFTP
        run: |
          docker build -f ./debian/Dockerfile -t ucipass/debian ./debian
          docker push ucipass/debian
