on: 
  push:
    paths:
    - 'dyndns*'
jobs:
  push-dyndns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Docker Build & Publish dyndns 
        run: |
          docker build -f ./dyndns/Dockerfile -t ucipass/dyndns ./dyndns
          docker push ucipass/dyndns 
