on: 
  push:
    paths:
      - 'openconnect*'
jobs:
  openconnect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Docker Build & Publish openconnect
        run: |
          docker build -f ./openconnect/Dockerfile -t ucipass/openconnect ./openconnect
          docker push ucipass/openconnect